spring:
  application:
    name: dsapp-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/dsapp_db
    username: dsapp_admin
    password: secure_pass_123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

logging:
  level:
    root: INFO
    liquibase: DEBUG
jwt:
  # Секрет должен быть не менее 256 бит (32 символа) для HS256.
  # В продакшене выносить в переменную окружения.
  secret: "jwt-demo-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm"
  access-token-expiration: 900000      # 15 минут в миллисекундах
  refresh-token-expiration: 604800000  # 7 дней в миллисекундах