spring.application.name=dsapp-backend
spring.docker.compose.file=docker/docker-compose.yml
spring.datasource.url=jdbc:postgresql://localhost:5433/dsapp_db

spring.datasource.username=dsapp_admin
spring.datasource.password=secure_pass_123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.url=jdbc:postgresql://localhost:5433/dsapp_db
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.liquibase.enabled=true
spring.liquibase.user=dsapp_admin
spring.liquibase.password=secure_pass_123